# Generated by Django 3.1.7 on 2021-05-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_department', models.TextField()),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('incident_location', models.CharField(max_length=100)),
                ('suspected_cause', models.TextField()),
                ('immediate_action_taken', models.TextField()),
                ('reported_by', models.CharField(max_length=100)),
                ('initial_severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.severity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.location')),
                ('sub_incident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.incidenttype')),
            ],
        ),
    ]
