# Generated by Django 3.1.7 on 2021-05-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='severity',
            options={'ordering': ['-name']},
        ),
    ]
