# Generated by Django 3.1.7 on 2021-05-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20210507_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='severity',
            options={},
        ),
    ]
