# Generated by Django 3.1.7 on 2021-05-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20210507_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='immediate_action_taken',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='suspected_cause',
            field=models.CharField(max_length=100),
        ),
    ]
